# Uncomment this line to define a global platform for your project
#platform :ios, '6.0'


target 'CoreDataTest' do
    pod 'CoreDataLite', :path => "../CoreDataLite.podspec"
end

target 'CoreDataTestTests' do
    pod 'CoreDataLite', :path => "../CoreDataLite.podspec"
end